steps:
  - name: gcr.io/cloud-builders/docker
    entrypoint: docker
    args: ['pull', 'gcr.io/$PROJECT_ID/umpiregpt:v1']
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/umpiregpt:v1', '-f', 'Dockerfile', '.', '--cache-from', 'gcr.io/$PROJECT_ID/umpiregpt:v1']
  - name: gcr.io/cloud-builders/docker
    args: ['push', 'gcr.io/$PROJECT_ID/umpiregpt:v1']
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - umpiregpt-v1
      - --image=gcr.io/$PROJECT_ID/umpiregpt:v1
      - --region=us-central1
      - --platform=managed
      - --allow-unauthenticated
      - --set-secrets=OPENAI_API_KEY=OPENAI_API_KEY:latest
      - --port=8000
      - --min-instances=1
      - --timeout=600s
    env:
      - 'USE_OPENAI=true'
      - 'KB_PATH=data/chunks/rules.chunks.jsonl'
