substitutions:
  _REGION: us-central1
  _MEMORY: "256Mi"
  _CPU: "1"
steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/umpiregpt:v1', '.']
    dir: '.'
  # Push the image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/umpiregpt:v1']
  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'run'
      - 'deploy'
      - 'umpiregpt-v1'
      - '--image=gcr.io/$PROJECT_ID/umpiregpt:v1'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--memory=${_MEMORY}'
      - '--cpu=${_CPU}'
      - '--allow-unauthenticated'
      - '--set-secrets=OPENAI_API_KEY=OPENAI_API_KEY:latest'
    entrypoint: 'gcloud'
images:
  - 'gcr.io/$PROJECT_ID/umpiregpt:v1'
