steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/$_REPO/$_SERVICE:$COMMIT_SHA', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/$_REPO/$_SERVICE:latest', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/$_REPO/$_SERVICE:latest']
images:
- 'us-central1-docker.pkg.dev/$PROJECT_ID/$_REPO/$_SERVICE:latest'
substitutions:
  _SERVICE: umpgpt-v1
  _LOCATION: us-central1
  _REPO: containers
