steps:
  - name: gcr.io/cloud-builders/docker
    entrypoint: docker
    args: ['pull', 'gcr.io/$PROJECT_ID/umpiregpt-base:v1']
    id: pull-base
    waitFor: ['-']
  - name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - |
        if git diff --name-only HEAD^ HEAD | grep -q Dockerfile.base; then
          docker build -t gcr.io/$PROJECT_ID/umpiregpt-base:v1 -f Dockerfile.base .
          docker push gcr.io/$PROJECT_ID/umpiregpt-base:v1
        else
          echo "No changes to Dockerfile.base, skipping base image build"
        fi
    id: build-and-push-base
    waitFor: ['pull-base']
  - name: gcr.io/cloud-builders/docker
    entrypoint: docker
    args: ['pull', 'gcr.io/$PROJECT_ID/umpiregpt:v1']
    id: pull-app
    waitFor: ['-']
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/umpiregpt:v1', '-f', 'Dockerfile', '.', '--cache-from', 'gcr.io/$PROJECT_ID/umpiregpt:v1']
    id: build-app
    waitFor: ['build-and-push-base', 'pull-app']
  - name: gcr.io/cloud-builders/docker
    args: ['push', 'gcr.io/$PROJECT_ID/umpiregpt:v1']
    id: push-app
    waitFor: ['build-app']
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:542.0.0
    entrypoint: gcloud
    args:
      - run
      - deploy
      - umpiregpt-v1
      - --image=gcr.io/$PROJECT_ID/umpiregpt:v1
      - --region=us-central1
      - --platform=managed
      - --allow-unauthenticated
      - --set-secrets=OPENAI_API_KEY=OPENAI_API_KEY:latest
      - --port=8000
      - --min-instances=1
      - --timeout=600s
    env:
      - 'USE_OPENAI=true'
      - 'KB_PATH=data/chunks/rules.chunks.jsonl'
    id: deploy
    waitFor: ['push-app']
