FROM python:3.11-slim
WORKDIR /umpiregpt
COPY requirements.txt .
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y build-essential libopenblas-dev
RUN pip install --no-cache-dir --upgrade pip==25.2
RUN pip install --no-cache-dir streamlit==1.39.0 requests==2.32.3
COPY src/app.py .
EXPOSE 8501
CMD ["streamlit", "run", "app.py", "--server.port", "8501", "--server.address", "0.0.0.0"]
